### ISSUE TITLE
Typo in CD (certificate of deposit) schema

### ISSUE THREAD

**Issue by dheerajkhardwal** [Sahamati/account-aggregator-standards#12]
https://github.com/Sahamati/account-aggregator-standards/blob/07598922d40901f573f28e91a2ad1412675e4566/schemas/certificates_of_deposit/cd.xsd#L131

This causes XML validation to fail due to `space` introduced in the attribute name.

**Comment by Swastyy** [comment]
Hi @dheerajkhardwal Is this issue solved?

**Comment by dheerajkhardwal** [comment]
@Swastyy Yes, this issue is resolved in #21. 
Closing this issue, thanks for pointing out.
